server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/IN22915804
    password: 12345
    username: IN22915804
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect